:func:`trio.move_on_after` and :func:`trio.fail_after` now sets the deadline upon entering the context manager, instead of at initialization. The vast majority of usage initialized them when entering and is therefore unaffected. But if you have code that looks like:

.. code-block:: python3

    cs = trio._move_on_after(5)
    ...
    with cs:
        ...


the deadline of the underlying :func:`trio.CancelScope` will now differ. If you want to fully preserve current behaviour you can rewrite it as

.. code-block:: python3

   cs = trio.move_on_at(trio.current_time() + 5)
   ...
   with cs:
       ...
